### ISSUE TITLE
Support for Remix v2 (with vite)

### ISSUE THREAD

**Issue by underfisk** [nrwl/nx-recipes#73]
Is there any plan for integrating Remix v2 (which brings Vite opt-in)?
If possible supporting custom server as so far i haven't been able to create my own server instance (e.g: image requiring websockets or any 3rd party integration)

**Comment by aaronksaunders** [comment]
just checking to see if anyone has successfully used nx with Remix v2 and vite?

**Comment by Coly010** [comment]
Hi!

We have moved our Remix support to the main Nx repo (https://github.com/nrwl/nx) and we have migrated it to use Remix v2. 

If there is a specific issue you're facing with it, could you raise an issue there so that I can delve deeper?
https://github.com/nrwl/nx/issues/new/choose

Thanks!

**Comment by oliveryasuna** [comment]
The examples still use Remix v1. Has anyone gotten it to work with v2 and has an example repo?
